spring:
  datasource:
    url: ${SPRING_DATASOURCE_URLL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
  
  config:
    import: optional:file:.env[.properties]

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
