spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASS}
    driver-class-name: org.postgresql.Driver
   
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  config:
    import: optional:file:.env[.properties]

# Service URLs with default values
user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8080}

auction:
  service:
    url: ${AUCTION_SERVICE_URL:http://localhost:8081}

server:
  port: 8082

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 